version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: machine-executor
    steps:
      - checkout

  build_docker_image:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts > /dev/null
            echo 'source $HOME/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Authenticate with google cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY"  > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - run:
          name: Build and Push Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/my-repo/mlops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/my-repo/mlops-app:latest

  deploy_to_gke:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -sLO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --client

      - run:
          name: Authenticate with google cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY"  > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      
      - run:
          name: Configure GKE
          command: |
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID

      - run:
          name: Install gke-gcloud-auth-plugin
          command: |
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
            echo 'export USE_GKE_GCLOUD_AUTH_PLUGIN=True' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Deploy to GKE
          command: |
              gcloud container clusters get-credentials $GKE_CLUSTER --region $GOOGLE_COMPUTE_REGION --project $GOOGLE_PROJECT_ID
              kubectl apply -f kubernetes-deployment.yaml

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - build_docker_image:
          requires:
            - checkout_code
      - deploy_to_gke:
          requires:
            - build_docker_image