name: CI/CD Deployement to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GKE_CLUSTER: "my-cluster"
    GKE_REGION: "us-central1"
    DEPLOYMENT_NAME: "mlops-app"
    REPOSITORY: "us-central1-docker.pkg.dev/mlops-463410/my-repo"
    IMAGE: "us-central1-docker.pkg.dev/mlops-463410/my-repo/mlops-app"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout-Repository
              uses: actions/checkout@v2

            - name: Authenticate with Google cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Configure GCloud
              run: |
                gcloud config set project $PROJECT_ID
                gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Building and Pushing Image
              run: |
                docker build -t $IMAGE:$GITHUB_SHA .
                docker push $IMAGE:$GITHUB_SHA
            
            - name: Get GKE credentials
              uses: google-github-actions/get-gke-credentials@v1
              with:
                cluster_name: ${{ env.GKE_CLUSTER }}
                location: ${{ env.GKE_REGION }}
                project_id: ${{ env.PROJECT_ID }}
                
            - name: Deploying to Kubernetes
              run: |
                kubectl apply -f kubernetes-deployment.yaml
                kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA